http {
    # Create rate limiters (in memory)
    # TODO: Migrate to Redis later for HA
    limit_req_zone $binary_remote_addr zone=main:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=auth:10m rate=5r/s;

    # Connection retry config
    proxy_next_upstream error timeout http_500 http_502 http_503;
    proxy_next_upstream_tries 2;
    proxy_next_upstream_timeout 5s;

    include /etc/nginx/conf.d/upstream.conf;
    include /etc/nginx/conf.d/default.conf;
}

events {}
