http {
    upstream auth_be {
        # Pre-opened connections to backend
        keepalive 32;
        # How long should cached connections be opened
        keepalive_timeout 60s;
        server backend:3000;
    }

    upstream products_be {
        keepalive 32;
        keepalive_timeout 60s;
        server backend:4000;
    }

    # Create rate limiters (in memory)
    # TODO: Migrate to Redis later for HA
    limit_req_zone $binary_remote_addr zone=main:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=auth:10m rate=5r/s;

    # Connection retry config
    proxy_next_upstream error timeout http_500 http_502 http_503;
    proxy_next_upstream_tries 2;
    proxy_next_upstream_timeout 5s;

    server {
        # Listening on HTTPS port with TLS and HTTP/2 enabled
        listen 443 ssl http2;

        # Certificate and private key locations, for HTTPS
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        # Support for TLS 1.2 and 1.3
        ssl_protocols TLSv1.2 TLSv1.3;
        # Setup cache for TLS handshakes to be reused, with timeout of 10m
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        # Allowed TLS ciphers (for TLS 1.2 mostly as it supports lots of ciphers)
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:!RC4:!3DES:!aNULL:!eNULL:!MD5:!DSS';
        ssl_prefer_server_ciphers on;

        # For how long should we keep an existing TCP connection alive for re-use
        keepalive_timeout 65s;
        # Max number of requests that be served within a connection before reuse
        keepalive_requests 999;

        # Sets HTTP version for nginx -> backend servers (1.1 is used for using keepalive)
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        # Timeouts for connecting / writing / reading from backend
        proxy_connect_timeout 5s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;

        # Timeouts for waiting for client headers / reads / writes
        client_header_timeout 12s;
        client_body_timeout 20s;
        send_timeout 60s;


        location /auth/ {
            limit_req zone=auth burst=10 nodelay;
            limit_req_status 429;
            proxy_pass http://auth_be/;
        }

        location /products/ {
            limit_req zone=main burst=20 nodelay;
            limit_req_status 429;
            proxy_pass http://products_be/;
        }

        location = /products/ws/prices/ {
            limit_req zone=main burst=20 nodelay;
            limit_req_status 429;
            proxy_pass http://products_be/ws/prices;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        # Hacky solution to merge both /health endpoints
        location = /health/ {
            auth_request /health_auth;
            proxy_pass http://products_be/health;
        }

        location = /health_auth {
            internal;
            proxy_pass http://auth_be/health;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }
    }

    server {
        listen 80;
        server_name _;
        # Redirect HTTP to HTTPS
        return 301 https://$host$request_uri;
    }
}

events {}
