upstream auth_be {
    # Pre-opened connections to backend
    keepalive 32;
    # How long should cached connections be opened
    keepalive_timeout 60s;
    server backend:3000;
}

upstream products_be {
    keepalive 32;
    keepalive_timeout 60s;
    server backend:4000;
}
