upstream auth_be {
    # Pre-opened connections to backend
    keepalive 32;
    # How long should cached connections be opened
    keepalive_timeout 60s;
    server {{ hostvars['backend']['ansible_host'] }}:3000;
}

upstream products_be {
    keepalive 32;
    keepalive_timeout 60s;
    server {{ hostvars['backend']['ansible_host'] }}:4000;
}
