---
- name: Install nginx
  ansible.builtin.apt:
    name: "nginx"

- name: Enable and run nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: TLS configuration
  ansible.builtin.import_tasks:
    file: tls.yml

- name: Copy configuration
  ansible.builtin.import_tasks:
    file: config.yml

- name: Install monitoring agents
  ansible.builtin.import_tasks:
    file: monitoring.yml
