---
- name: Include vault vars
  ansible.builtin.include_vars:
    file: vars/vault.yml

- name: Install keepalived
  ansible.builtin.apt:
    name:
      - keepalived
    state: present

- name: Create keepalived_script user for running scripts
  ansible.builtin.user:
    name: keepalived_script
    system: true
    state: present

- name: Copy health check script
  ansible.builtin.copy:
    src: files/check_nginx.sh
    dest: /usr/local/bin/check_nginx.sh
    mode: "0550"
    owner: keepalived_script
    group: keepalived_script

- name: Install awscli
  community.general.snap:
    name:
      - aws-cli
    classic: true
    state: present
  when: env_type | default('local') == 'aws'

- name: Copy AWS eip claim script
  ansible.builtin.template:
    src: templates/claim_eip.sh.j2
    dest: /usr/local/bin/claim_eip.sh
    mode: "0550"
    owner: keepalived_script
    group: keepalived_script
  when: env_type | default('local') == 'aws'

- name: Enable keepalived service
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true

- name: Copy keepalived configuration
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: Restart keepalived
