- name: Common config
  hosts: all
  become: true
  tags:
    - common
  roles:
    - common

- name: Backend workload config
  hosts: backend
  become: true
  tags:
    - backend
  roles:
    - backend

- name: Nginx hosts config
  hosts: nginx
  become: true
  tags:
    - nginx
  roles:
    - nginx

- name: Keepalived hosts config
  hosts: keepalived
  become: true
  tags:
    - keepalived
  roles:
    - keepalived

- name: Monitoring host config
  hosts: monitoring
  become: true
  tags:
    - monitoring
  roles:
    - monitoring
