- name: Backend workload config
  hosts: backend
  become: true
  roles:
    - backend

- name: Nginx hosts config
  hosts: nginx
  become: true
  roles:
    - nginx

- name: Keepalived hosts config
  hosts: keepalived
  become: true
  roles:
    - keepalived
