name: CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write # Required for requesting the JWT token
  contents: read # Required for actions/checkout

jobs:
  apply-tf-and-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Download Plan Artifact
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: ci.yml
          name: terraform-plan
          path: "./infra/terraform"

      - name: Setup Ansible
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.0"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Ansible
        working-directory: ./infra/ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install ansible-lint
          ansible-galaxy collection install -r requirements.yml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./infra/terraform
        run: terraform init

      - name: Apply TF deployment
        working-directory: ./infra/terraform
        env:
          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
        run: |
          echo $SSH_KEY_FILE > ssh.pem
          terraform apply -var "ssh_key_name=$SSH_KEY_NAME" -var "ssh_key_file=ssh.pem" -auto-approve tfplan
          shred -u ssh.pem

      - name: Invoke Ansible action
        working-directory: ./infra/terraform
        env:
          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
        run: |
          echo $SSH_KEY_FILE > ssh.pem
          terraform apply -invoke=action.ansible_playbook_run.ansible -var "ssh_key_name=$SSH_KEY_NAME" -var "ssh_key_file=ssh.pem" -auto-approve
          shred -u ssh.pem
