name: CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  id-token: write # Required for requesting the JWT token
  contents: read # Required for actions/checkout

jobs:
  lint-tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./infra/terraform
        run: terraform init

      - name: Check TF formatting
        working-directory: ./infra/terraform
        run: terraform fmt -check

      - name: Validate TF code
        working-directory: ./infra/terraform
        run: terraform validate

      - name: Run trivy on TF code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-dir: "./infra/terraform"
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1"
          severity: "HIGH,CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Plan TF deployment
        working-directory: ./infra/terraform
        env:
          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
        run: |
          echo $SSH_KEY_FILE > ssh.pem
          terraform plan -var "ssh_key_name=$SSH_KEY_NAME" -var "ssh_key_file=ssh.pem"
          shred -u ssh.pem

  lint-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Ansible
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.0"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Ansible
        working-directory: ./infra/ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install ansible-lint
          ansible-galaxy collection install -r requirements.yml

      - name: Ansible Syntax Check
        working-directory: ./infra/ansible
        env:
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $VAULT_PASS > .vault_pass
          ansible-playbook site.yml --syntax-check
          shred -u .vault_pass

      - name: Ansible Lint
        working-directory: ./infra/ansible
        env:
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $VAULT_PASS > .vault_pass
          ansible-lint
          shred -u .vault_pass

      # - name: Run Checkov Action for Ansible (SAST)
      #   uses: bridgecrewio/checkov-action@master
      #   with:
      #     directory: ./infra/ansible
      #     framework: ansible
