name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write # Required for requesting the JWT token
  contents: read # Required for actions/checkout

jobs:
  lint-tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./infra/terraform
        run: terraform init

      - name: Check TF formatting
        working-directory: ./infra/terraform
        run: terraform fmt -check

      - name: Validate TF code
        working-directory: ./infra/terraform
        run: terraform validate

      - name: Plan TF deployment
        working-directory: ./infra/terraform
        env:
          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $VAULT_PASS > ../ansible/.vault_pass
          echo $SSH_KEY_FILE > ssh.pem
          terraform plan -var "ssh_key_name=$SSH_KEY_NAME" -var "ssh_key_file=ssh.pem" -out=tfplan
          shred -u ../ansible/.vault_pass
          shred -u ssh.pem

      - name: Upload TF plan artifact
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          path: "./infra/terraform/tfplan"
          retention-days: 1

  lint-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Ansible
        working-directory: ./infra/ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install ansible-lint
          ansible-galaxy collection install -r requirements.yml

      - name: Ansible Syntax Check
        working-directory: ./infra/ansible
        env:
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $VAULT_PASS > .vault_pass
          ansible-playbook site.yml --syntax-check
          shred -u .vault_pass

      - name: Ansible Lint
        working-directory: ./infra/ansible
        env:
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $VAULT_PASS > .vault_pass
          ansible-lint
          shred -u .vault_pass

  apply-tf-and-ansible:
    runs-on: ubuntu-latest
    needs: [lint-tf, lint-ansible]
    # Only run deployment on pushes to master or manual dispatches, NOT on pull requests
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v7

      - name: Download Plan Artifact
        uses: actions/download-artifact@v7
        with:
          name: terraform-plan
          path: "./infra/terraform"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Ansible
        working-directory: ./infra/ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install ansible-lint
          ansible-galaxy collection install -r requirements.yml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./infra/terraform
        run: terraform init

      - name: Apply TF deployment
        working-directory: ./infra/terraform
        env:
          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $VAULT_PASS > ../ansible/.vault_pass
          echo $SSH_KEY_FILE > ssh.pem
          terraform apply -var "ssh_key_name=$SSH_KEY_NAME" -var "ssh_key_file=ssh.pem" -auto-approve tfplan
          shred -u ../ansible/.vault_pass
          shred -u ssh.pem

      - name: Invoke Ansible action
        working-directory: ./infra/terraform
        env:
          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $VAULT_PASS > ../ansible/.vault_pass
          echo $SSH_KEY_FILE > ssh.pem
          terraform apply -invoke=action.ansible_playbook_run.ansible -var "ssh_key_name=$SSH_KEY_NAME" -var "ssh_key_file=ssh.pem" -auto-approve
          shred -u ../ansible/.vault_pass
          shred -u ssh.pem
