name: Destroy Resources workflow

on:
  workflow_dispatch:

permissions:
  id-token: write # Required for requesting the JWT token
  contents: read # Required for actions/checkout

jobs:
  apply-tf-and-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./infra/terraform
        run: terraform init

      - name: Destroy TF resources
        working-directory: ./infra/terraform
        env:
          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
        run: |
          echo $SSH_KEY_FILE > ssh.pem
          terraform destroy -var "ssh_key_name=$SSH_KEY_NAME" -var "ssh_key_file=ssh.pem" -auto-approve
          shred -u ssh.pem
